### ISSUE TITLE
Not able to reassign a deleted instances inventory number

### ISSUE THREAD

**Issue by ChrisDeh** [rmsv2/rmsv2#9]
After deleting a Instance of a device, it is not possible to reassign the previously use inventory number again. Error Message: "Instance mit diesem Inventarnummer existiert bereits" (Would be nice to fix the spelling too)

**Comment by JulianJacobi** [comment]
I have improved now the instance delete mechanism, if the instance was never a part of a reservation or rental ticket it will be really delete. If there was or is such a relation then the instance cannot be really deleted without consistency problems in the whole system, so in such cases the instance will only be deactivated so it shows up in rental tickets and reservations furthermore.

Spelling was fixed in 43beed6
